(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.DepositoEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const COLS=8,SKUS=5;const initial=[null,0,1,null,2,null,3,null,null,null,null,null,null,null,null,null,null,1,0,2,null,3,4,null,null,2,3,4,null,0,1,null,null,null,null,null,null,null,null,null,null,4,2,3,null,1,0,null];
const count=a=>a.reduce((q,x)=>(q[x]=(q[x]||0)+1,q),Array(SKUS).fill(0));const distance=(a,b)=>Math.abs(Math.floor(a/COLS)-Math.floor(b/COLS))+Math.abs(a%COLS-b%COLS);
const settings={calm:{arrival:12,order:20},normal:{arrival:10,order:17},intense:{arrival:8,order:14}};
class Game{
 constructor(mode='normal'){this.mode=mode in settings?mode:'normal';this.frequency=settings[this.mode];this.minute=0;this.credits=100;this.storage=initial.slice();this.capacity=48;this.quarantine=Array(6).fill(null);this.outside=[];this.orders=[];this.arrivals=[];this.nextId=1;this.active=null;this.message='Los pedidos se acumulan. Arrastrá los cuadrados.';this.lost=false;this.completed=0;this.queueCapacity=5;this.nextArrival=5;this.nextOrder=9;this.generatedSupply=count(this.storage.filter(x=>x!==null));this.generateTo(180)}
 generateTo(until){while(Math.min(this.nextArrival,this.nextOrder)<=until){if(this.nextArrival<=this.nextOrder){let k=this.arrivals.length,sku=k%SKUS,items=[sku,(k%3===0?(sku+1)%SKUS:sku)];this.arrivals.push({id:this.nextId++,at:this.nextArrival,items,status:'future'});for(let x of items)this.generatedSupply[x]++;this.nextArrival+=this.frequency.arrival}else{let k=this.orders.length,items=[];for(let j=0;j<3;j++){let ranked=Array.from({length:SKUS},(_,i)=>i).sort((a,b)=>this.generatedSupply[b]-this.generatedSupply[a]||((a-k+SKUS)%SKUS)-((b-k+SKUS)%SKUS));let sku=ranked[0];items.push(sku);this.generatedSupply[sku]--}this.orders.push({id:this.nextId++,at:this.nextOrder,items,prepared:[],status:'future'});this.nextOrder+=this.frequency.order}}}
 debit(n){this.credits-=n;if(this.credits<=0){this.credits=0;this.lost=true;this.message='Sin créditos. Fin de la partida.'}}
 log(x){if(!this.lost)this.message=x}
 accessible(){const seen=new Set(),stack=[];for(let r=0;r<this.storage.length/COLS;r++){let i=r*COLS;if(this.storage[i]===null){seen.add(i);stack.push(i)}}while(stack.length){let i=stack.pop(),r=Math.floor(i/COLS),c=i%COLS;for(let n of [c>0?i-1:-1,c<7?i+1:-1,r>0?i-8:-1,r<this.storage.length/COLS-1?i+8:-1])if(n>=0&&this.storage[n]===null&&!seen.has(n)){seen.add(n);stack.push(n)}}return seen}
 canReachStock(i){if(this.storage[i]===null)return false;if(i%COLS===0)return true;let r=Math.floor(i/COLS),c=i%COLS,open=this.accessible();return [c>0?i-1:-1,c<7?i+1:-1,r>0?i-8:-1,r<this.storage.length/COLS-1?i+8:-1].some(n=>open.has(n))}
 queue(){return this.orders.filter(o=>o.status==='queued')}
 advance(n=1){for(let j=0;j<n&&!this.lost;j++){this.minute++;this.generateTo(this.minute+170);this.debit(1);let arrived=false;for(const a of this.arrivals)if(a.status==='future'&&a.at<=this.minute){a.status='arrived';arrived=true;this.outside.push(...a.items.map(sku=>({sku,arrivalId:a.id,since:this.minute})));this.log('Llegó mercadería a cuarentena.')}this.admit();if(arrived&&this.outside.length)this.debit(12*this.outside.length);for(const o of this.orders)if(o.status==='future'&&o.at<=this.minute){o.status=this.queue().length<this.queueCapacity?'queued':'overflow';if(o.status==='overflow'){this.debit(18);this.log('Cola llena: pedido en espera afuera.')}else this.log('Nuevo pedido en la cola.')}for(const o of this.orders){if(o.status==='queued'&&this.minute>o.at+3)this.debit(2);if(o.status==='overflow')this.debit(4)}for(const q of this.quarantine)if(q&&this.minute>q.since+5&&(this.minute-q.since-5)%2===0)this.debit(1);for(const x of this.outside)this.debit(3);if(this.credits<=0){this.credits=0;this.lost=true;this.message='Sin créditos. Fin de la partida.'}}return !this.lost}
 admit(){let moved=0;while(this.outside.length){let i=this.quarantine.findIndex(x=>x===null);if(i<0)break;this.quarantine[i]={...this.outside.shift(),entered:this.minute};moved++}if(moved)this.log(moved+' unidades ingresaron a cuarentena.')}
 moveStorage(from,to){if(this.lost||from===to||this.storage[from]==null||this.storage[to]!==null||!this.canReachStock(from)||!this.accessible().has(to))return false;let cost=1+Math.ceil(distance(from,to)/4);this.debit(cost);if(this.lost)return false;this.storage[to]=this.storage[from];this.storage[from]=null;this.log('Movimiento interno: −'+cost+' créditos.');return true}
 release(qIndex,to){let item=this.quarantine[qIndex];if(this.lost||!item||this.storage[to]!==null||!this.accessible().has(to)||this.minute<item.since+2)return false;let cost=2+Math.ceil((to%COLS+1)/4);this.debit(cost);if(this.lost)return false;this.storage[to]=item.sku;this.quarantine[qIndex]=null;let source=this.arrivals.find(a=>a.id===item.arrivalId);if(source&&!this.quarantine.some(q=>q&&q.arrivalId===source.id)&&!this.outside.some(q=>q.arrivalId===source.id))source.status='done';this.log('Mercadería ubicada: −'+cost+' créditos.');return true}
 select(id){let o=this.orders.find(x=>x.id===id&&x.status==='queued');if(!o)return false;this.active=id;this.log('Pedido seleccionado. Arrastrá sus colores a Pedidos.');return true}
 pick(i){let o=this.orders.find(x=>x.id===this.active&&x.status==='queued'),sku=this.storage[i];if(this.lost||!o||sku==null||!this.canReachStock(i))return false;let needs=count(o.items),ready=count(o.prepared);if(ready[sku]>=needs[sku])return false;let cost=1+Math.ceil((i%COLS+1)/3);this.debit(cost);if(this.lost)return false;this.storage[i]=null;o.prepared.push(sku);this.log('Pedido '+o.prepared.length+'/'+o.items.length+' preparado.');return true}
 dispatch(id){let o=this.orders.find(x=>x.id===id&&x.status==='queued');if(this.lost||!o||o.prepared.length!==o.items.length)return false;let delay=this.minute-o.at,reward=Math.max(8,o.items.length*9+12-Math.max(0,delay-3)*2);this.credits+=reward;o.status='done';this.completed++;if(this.active===id)this.active=null;let waiting=this.orders.find(x=>x.status==='overflow');if(waiting){waiting.status='queued';this.log('Pedido despachado: +'+reward+'. Entró otro a la cola.')}else this.log('Pedido despachado: +'+reward+' créditos.');return true}
 expand(zone){if(this.lost)return false;if(zone==='q'){if(this.credits<=75)return false;this.debit(75);this.quarantine.push(...Array(3).fill(null));this.log('Cuarentena ampliada: +3 posiciones.');return true}if(zone==='storage'&&this.capacity<64){if(this.credits<=60)return false;this.debit(60);this.storage.push(...Array(8).fill(null));this.capacity+=8;this.log('Depósito ampliado: +8 posiciones.');return true}return false}
}
return {Game,count,distance,settings};});
