(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.DepositoEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const COLS=8,ROWS=6,SKUS=5;const initial=[0,null,1,2,0,null,3,null,1,0,null,2,null,1,null,3,2,null,0,1,null,3,null,null,0,2,null,1,3,null,0,null,1,null,2,0,null,3,null,null,0,1,null,2,null,3,null,null];
const count=a=>a.reduce((q,x)=>(q[x]=(q[x]||0)+1,q),Array(SKUS).fill(0));
const distance=(a,b)=>Math.abs(Math.floor(a/COLS)-Math.floor(b/COLS))+Math.abs(a%COLS-b%COLS);
class Game{
 constructor(){this.minute=0;this.credits=100;this.storage=initial.slice();this.capacity=48;this.quarantine=Array(6).fill(null);this.outside=[];this.orders=[];this.arrivals=[];this.nextId=1;this.active=null;this.message='Tocá Pedidos para elegir una salida.';this.lost=false;this.completed=0;this.cycle=0;this.generateTo(160)}
 generateTo(until){while(this.cycle*12<until){let k=this.cycle++,base=5+k*12,sku=(k+2)%SKUS,second=(k+3)%SKUS;let arriving=[sku,sku,second];this.arrivals.push({id:this.nextId++,at:base,items:arriving,status:'future'});let orderItems=k<3?[k%4,(k+1)%4,(k+2)%4]:[sku,sku,second];this.orders.push({id:this.nextId++,at:base+6,items:orderItems,prepared:[],status:'open',penalizedThrough:base+8});}}
 debit(n){this.credits-=n;if(this.credits<=0){this.credits=0;this.lost=true;this.message='Sin créditos. Fin de la partida.'}}
 log(x){if(!this.lost)this.message=x}
 advance(n=1){for(let j=0;j<n&&!this.lost;j++){this.minute++;this.generateTo(this.minute+145);this.credits-=1;let arrived=false;for(const a of this.arrivals){if(a.status==='future'&&a.at<=this.minute){a.status='outside';arrived=true;this.outside.push(...a.items.map(sku=>({sku,arrivalId:a.id,since:this.minute})));this.log('Llegó mercadería. Necesita lugar en cuarentena.')}}this.admit();if(arrived&&this.outside.length)this.debit(12*this.outside.length);for(const q of this.quarantine){if(q&&this.minute>q.since+5&&(this.minute-q.since-5)%2===0)this.debit(1)}for(const x of this.outside){this.debit(3)}for(const o of this.orders){if(o.status!=='open')continue;if(this.minute>o.at+2&&this.minute<=o.at+10)this.debit(2);if(this.minute>o.at+10){o.status='cancelled';this.debit(18);this.log('Pedido cancelado: −18 créditos.')}}if(this.credits<=0){this.credits=0;this.lost=true;this.message='Sin créditos. Fin de la partida.'}}return !this.lost}
 admit(){let moved=0;while(this.outside.length){let index=this.quarantine.findIndex(x=>x===null);if(index<0)break;let item=this.outside.shift();this.quarantine[index]={...item,entered:this.minute};moved++}if(moved)this.log(moved+' unidades ingresaron a cuarentena.');}
 moveStorage(from,to){if(this.lost||from===to||this.storage[from]==null||this.storage[to]!==null)return false;let cost=1+Math.ceil(distance(from,to)/4);this.debit(cost);if(this.lost)return false;this.storage[to]=this.storage[from];this.storage[from]=null;this.advance(1);this.log('Movimiento interno: −'+cost+' créditos.');return true}
 release(qIndex,to){let item=this.quarantine[qIndex];if(this.lost||!item||this.storage[to]!==null||this.minute<item.since+2)return false;let cost=2+Math.ceil((to%COLS+1)/4);this.debit(cost);if(this.lost)return false;this.storage[to]=item.sku;this.quarantine[qIndex]=null;let source=this.arrivals.find(a=>a.id===item.arrivalId);if(source&&!this.quarantine.some(q=>q&&q.arrivalId===source.id)&&!this.outside.some(q=>q.arrivalId===source.id))source.status='done';this.advance(1);this.log('Mercadería ubicada: −'+cost+' créditos.');return true}
 select(id){let o=this.orders.find(x=>x.id===id&&x.status==='open');if(!o)return false;this.active=id;this.log('Pedido seleccionado. Arrastrá sus colores a Pedidos.');return true}
 pick(index){let o=this.orders.find(x=>x.id===this.active&&x.status==='open'),sku=this.storage[index];if(this.lost||!o||sku==null)return false;let needs=count(o.items),ready=count(o.prepared);if(ready[sku]>=needs[sku])return false;let cost=1+Math.ceil((index%COLS+1)/3);this.debit(cost);if(this.lost)return false;this.storage[index]=null;o.prepared.push(sku);this.advance(1);this.log('Pedido '+o.prepared.length+'/'+o.items.length+' preparado.');return true}
 dispatch(id){let o=this.orders.find(x=>x.id===id&&x.status==='open');if(this.lost||!o||o.prepared.length!==o.items.length)return false;let delta=this.minute-o.at,reward=delta< -2?Math.floor((o.items.length*8+10)*.65):delta<=2?o.items.length*8+10:Math.max(6,o.items.length*8+10-3*(delta-2));this.credits+=reward;o.status='done';this.completed++;if(this.active===id)this.active=null;this.log('Pedido despachado: +'+reward+' créditos'+(delta>2?' (tarde).':delta< -2?' (temprano).':' (a tiempo).'));return true}
 expand(zone){if(this.lost)return false;if(zone==='q'){if(this.credits<=75)return false;this.debit(75);this.quarantine.push(...Array(3).fill(null));this.log('Cuarentena ampliada: +3 posiciones.');return true}if(zone==='storage'&&this.capacity<64){if(this.credits<=60)return false;this.debit(60);this.storage.push(...Array(8).fill(null));this.capacity+=8;this.log('Depósito ampliado: +8 posiciones.');return true}return false}
}
return {Game,count,distance};});
